[package]
name = "good-foods"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = "1"
serde_valid = "1"
serde_json = "1"
futures-util = "0.3"
thiserror = "2"
mime = "0.3"
actix-json-validator = { version = "0.1.0", path = "../../.." }
