[package]
name = "actix-json-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = "1.0.218"
serde_valid = "1.0.5"
serde_json = "1.0.139"
futures-util = "0.3.31"
thiserror = "2.0.11"
mime = "0.3.17"