name: Build and Test

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_lib:
    name: Build and test library
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        directory:
          - ./
          - ./docs/examples/good-foods
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Set up Clippy
        run: rustup component add clippy
      - name: Run Clippy
        working-directory: ${{ matrix.directory }}
        run: cargo clippy -- -D warnings # TODO: replace with `cargo clippy -- -W clippy::pedantic -D warnings`
      - name: Check formatting
        working-directory: ${{ matrix.directory }}
        run: cargo fmt -- --check
      - name: Build
        working-directory: ${{ matrix.directory }}
        run: cargo build --verbose
      - name: Test
        working-directory: ${{ matrix.directory }}
        run: cargo test --verbose
